### ISSUE TITLE
Programatically get a project's zones and political districts based on the project's GIS assets

### ISSUE THREAD

**Issue by smcalilly** [fpdcc/ccfp-asset-dashboard#126]
Will also need to remove this from the project edit form and instead show a list of zones/districts

**Comment by smcalilly** [comment]
We need to get the boundaries of these zones

**Comment by smcalilly** [comment]
There are several pieces to do this. At a high level:
- Add a geometry field to the district and zone models to have the boundaries
- Write import script to associate the boundaries from their GIS database to our models
- Add attribute to the project model that calculates the districts/zones for a project
- List the districts/zones based on the project model attribute

At a low level:

## 1. Add geometry field to these models
- [ ] HouseDistrict
- [ ] SenateDistrict
- [ ] CommissionerDistrict
- [ ] Zone

Alternatively, we could have a new Boundary model with a geometry and then relate each model to it.

## 2. Import boundaries from their GIS database
Their `pinus` has these tables:
- [ ] il_house_cb_2017_17_sldl_500k_cc
- [ ] il_senate_cb_2017_17_sldu_500k_cc
- [ ] commdistricts
- [ ] zones

One problem with these data: the house and senate districts are a specific year, so this will break whenever new house/senate boundaries are drawn and a new table is added with the new boundaries.

## 3. Add attribute to Project model for getting the boundaries
I'm not sure the best approach here. Using a phase's GIS assets, we'll need to find the intersection of each asset with each district/zone boundary.
- Do we want an attribute that calculates the boundaries on the fly (meaning it gets the boundaries each time a Project is queried)? This could be inefficient.
- Alternatively, we could somehow save the districts/zones whenever a GIS asset is saved.

## List the districts/zones in the Project detail view/UI
We'll need to figure out our strategy for step 3 before we can do this. Once we figure out that, this piece should be straightfoward.

**Comment by fgregg** [comment]
sounds good.

write the import_shape script assuming that we have the data in the repo somewhere as geojson already.
