### ISSUE TITLE
project and phase page design

### ISSUE THREAD

**Issue by glw** [fpdcc/ccfp-asset-dashboard#136]
I know that we are not set on the design yet, but I would like to add some comments now before that part gets underway... We would like to see the project and phases page designs to be combined in a way as that you can see most if not all data on a single page for a project and its phases. We understand that may cause more scrolling, but we think that will be preferred to most over clicking back and forth between phases, assets, etc.  I can discuss this more with you @smcalilly on our Fri call if you'd like.

**Comment by smcalilly** [comment]
closed with PR #160
