### ISSUE TITLE
Phase and funding forms on one page

### ISSUE THREAD

**Issue by smcalilly** [fpdcc/ccfp-asset-dashboard#156]

**Comment by smcalilly** [comment]
@xmedr when wireframing, be sure to allow one or more funding sources to be added.

**Comment by xmedr** [comment]
@smcalilly Ah heard, so the potential to add more than one funding source at a time, gotcha.

**Comment by smcalilly** [comment]
@xmedr that looks nice. i added a comment on the moqup.

one thing to think about: how would the form submission work from a code point of view? the html form is setup to submit a post request to the phase view. adding another "save funding" button would require a new endpoint. submitting two separate forms on one html page is kind of a confusing pattern.

with that in mind, would it be possible to combine the two forms so they're submitted to the same endpoint? this would let us simply the UI and only have one "save" button. django inline forms kind of solve this. here's an example (with a rough ui): https://medium.com/@adandan01/django-inline-formsets-example-mybook-420cc4b6225d they simply the form submission with one button.

**Comment by smcalilly** [comment]
> submitting two separate forms on one html page is kind of a confusing pattern.
in other words:

clicking "save phase" sends a post request to the `projects/phases/edit/<int:pk>/` url. clicking "save funding" sends a post request to the `projects/phases/<int:pk>/funding/update/`. it would be nice to consolidate those to a single url since they're on the same page.

just something to keep in mind. this could get complicated but maybe i'm overthinking it?

also, we might need some javascript to render the the phase funding forms as a user clicks "add another source". which adds to the complexity.

**Comment by xmedr** [comment]
@smcalilly Got a [version 2](https://app.moqups.com/XwcOHCqTtBejrK2NNT2trl2tc2dhupKh/view/page/ad64222d5) up. Notable changes are that the button at the top right changed to "Save All Changes" from "Save Phase", and the add funding box got merged with the funding list box. Also responded to your comment about the edit button

![image](https://github.com/fpdcc/ccfp-asset-dashboard/assets/114717958/3d7c6f46-e844-4359-906d-fedcc71de760)

So with one "save all" button, I'm hoping that this starts to get us towards having just one url for the update. And it looks like the article you sent has an example of them using some javascript to add a new row, so maybe we can borrow from that when the time comes.

**Comment by xmedr** [comment]
@smcalilly I've got a couple ideas I wanted to get some feedback on about how we can get those multiple FundingStreamForms to submit.

### 1) Using Javascript to submit separate forms
Reading through this [SO answer](https://stackoverflow.com/a/36715516), maybe we could render each `FundingStreamForm` as a separate `<form>` element, and add a JS `onlick()` to the Save All Changes button that takes every form on the page and submits them as individual forms. The answer even talks about using that JS to allow the user to make as many forms as they want.

This feels like an okay approach so far, but I haven't tried this out yet.

### 2) Grouping form sets through unique names
This was my initial thought, but it's more convoluted and I'm not sure it would work. Like we talked about, within the `PhaseForm`, we can have a `funding_stream` field containing the `FundingStreamForm`, and use a loop in the template to make a few funding forms. (This example doesn't consider dynamically setting the number of forms, so for simplicity's sake we'll say 3 instances.)

If it's possible, we might be able to make these forms in such a way that each input's `name` can have a suffix with a number. Something like `name="{{field.name}}_{{i}}"` equating to `year_0`, `year_1`, and `year_2`

```
 {% for i in range %}  # let's say range goes from 0 to 2 for three instances
   <div class="row">
   {% for field in form.funding_streams %}
     <div class="col-md-2">
       <input name="{{field.name}}_{{i}}" type=(field-type-accessor) value=(field-value-accessor) .... />
     </div>
   {% endfor %}
   </div>
 {% endfor %}
```

Then in the view, we might be able to use the suffix numbers for each field to both group submitted fields into `FundingStreamForm`s and instantiate as many of those forms as needed.

An issue with this are that I haven't yet been able to successfully recreate the input with all it's necessary attributes.

**Comment by smcalilly** [comment]
@xmedr these are some good ideas - thanks for sharing.

Yeah we can definitely do all of this in javascript. I was trying to keep things in django form-land but you're right that we could get away with submitting them via an api.

With number two, you might could render those inputs with javascript rather than the Django templating language. And then you can capture the entire form input in the PhaseUpdateView, including the inputs you rendered in javascript. So you'd basically use the FundingStreamForm in the view only to capture/validate the data.

One thing you'll need to consider either way — if the update view has any existing funding streams, you'll need to serve those up as inputs in the django template. So with either approach, you'll have to render in the template any instances of the FundingStreamForm (which are hydrated with the funding stream's data so you'll need the instance's id/pk), plus be able to add new inputs with javascript.

So I guess either way you'll need to generate the form inputs in javascript, and the question is whether to submit them via api (option 1) or with the phase form (option 2).

**Comment by smcalilly** [comment]
@xmedr thinking more about your javascript proposal, if you went that route, it would probably be best to submit the form after each funding stream is "added" (after a click event that submits the payload to the api), rather than submitting them all at once whenever the user clicks the main "save phase" button.

have you had more time to think about either of the options? i'm wondering what you're leaning towards.

**Comment by xmedr** [comment]
@smcalilly and on an simpler note, thankfully getting existing funding streams into editable fields and also getting js to add more rows to the dom for new sources wasn't difficult at all!

![add_sources](https://github.com/fpdcc/ccfp-asset-dashboard/assets/114717958/067e050d-9f9f-4c2a-9655-27ceb7f642ba)

**Comment by xmedr** [comment]
I'll be picking this back up!

@jim-z Just some questions in regards to you mentioning alerting users when they haven't filled out some fields on the phase edit page. Were you thinking:
- Informing users navigating away from the edit page that they haven't added funding sources? 
- Or making that mandatory upon creating a phase? (I'm not sure if in your process you folks can have a phase without funding, but as of right now in this app that can exist)
- Or something else entirely?

**Comment by jim-z** [comment]
If it's an easy add, I think just a note informing users that they haven't added funding sources when navigating away would suffice.  There are instances when phases are added without funding secured/known so wouldn't want to make it mandatory.
