### ISSUE TITLE
Scoring: Socio Econ Dist

### ISSUE THREAD

**Issue by glw** [fpdcc/ccfp-asset-dashboard#163]
Socio Econimic Distribution, looks like that is not currently in the database. I will get the latest version of this data and import into the database.

0 - no communities of need within 1 mile of project
1 - project is within 1 mile of an economically disconnected (EDA) or disinvested (DA) area
2 - project is within 1 mile of multiple EDA or DA’s
3 - project is within one mile of an overlapping area ("both" category in CMAP data) 
4 - project touches or is within boundary of EDA or DA
5 - project touches or is within boundary of "both" area

![image](https://user-images.githubusercontent.com/556205/160672801-2b5cc6e7-e03e-4319-bc84-477d11fd54f3.png)

https://www.cmap.illinois.gov/2050/maps/eda

**Comment by glw** [comment]
@smcalilly the new table is in the production db "pinus.cmap_disinvested_and_eda" Let me know if that is ok. Or if you'd like me to resend a db export or the table itself. 

The relevant column is named "displaygro", possible values are : "Disinvested", "Economically Disconnected Area", "Both". 
NULL values should be ignored.

**Comment by fgregg** [comment]
* Within 1 mile, what percentage of the land is EDA/DA? 
* Bonus for land is both EDA and DA

**Comment by smcalilly** [comment]
> @smcalilly the new table is in the production db "pinus.cmap_disinvested_and_eda" Let me know if that is ok. Or if you'd like me to resend a db export or the table itself.

@glw would it be possible to send a db export with the new table? That way I can work with it in my local development environment.
