### ISSUE TITLE
Improve CIP table

### ISSUE THREAD

**Issue by smcalilly** [fpdcc/ccfp-asset-dashboard#166]
Add these columns:
- [x] Name
- [x] Description
- [x] Zone
- [x] Phase
- [x] Year
- [x] Quarter
- [x] Cost (This comes from Update Phase window)
- [ ] Secured Funding (This comes from Phase Funding window)
- [x] Score
- [x] Funding Source (? this was my idea when they were talking about grants and secured funding)
- [  ] make sure CSV export creates unique rows for each funding stream

**Comment by smcalilly** [comment]
@fgregg Do you have any thoughts on how to represent these rows in a table? The listed columns are a combination of both a phase and a funding source, so these could be rows segmented by funding or rows combined by phase. We also have a requirement of exporting this data nicely into a CSV.

Some ideas:
1. Have phase as a row and then the funding sources be subrows, [kind of like this](https://www.google.com/search?q=table+with+rows+and+subrows&tbm=isch&ved=2ahUKEwjB4KOvq4_3AhWgQkIHHcIqAzwQ2-cCegQIABAA&oq=table+with+rows+and+subrows&gs_lcp=CgNpbWcQA1CbBFieDWDlD2gAcAB4AIABSogBuQWSAQIxMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=r91VYoHNJaCFieoPwtWM4AM&bih=676&biw=1423&client=firefox-b-1-d#imgrc=qOM41zg4A0qqRM).
    - [Our table library can do this](https://react-table.tanstack.com/docs/examples/sub-components) but it clicks to open the subrows
    - This might be able to export to CSV the way we want it (not sure right now but I bet we could figure it out)
2. List each phase and then combine the funding details into a funding column
    - In a funding column, include some sort of drop down or popup that you can click/hover over to show details about the funding
3. Treat each funding source as an individual row
    - This wouldn't work if a phase didn't have funding, unless we created a sensible default. (Though at the CIP planning stage could we assume there would always be some funding source?)
    - This way would export to csv better
    - It would look kind of like this:
       - project_1,phase_1,description,**funding_stream_1**,etc
       - project_1,phase_1,description,**funding_stream_2**,etc
       - project_1,phase_2,description,**no funding**,etc
       - project_1,phase_3,description,**funding_stream_21**,etc

**Comment by fgregg** [comment]
We should export the data to csv as 3 (because it will be better for filtering and sorting)

For the website, i like 1.

**Comment by smcalilly** [comment]
> Secured Funding (This comes from Phase Funding window)

I removed this from the columns because it's redundant with the subrow/table approach. We can bring this up when we demo again and see if that's okay.
