### ISSUE TITLE
add all sections

### ISSUE THREAD

**Issue by smcalilly** [fpdcc/ccfp-asset-dashboard#200]
Add these sections:

i.      Civil
ii.      Landscape Architecture
iii.      Building Architecture
iv.      Landscape Maintenance
v.      Facilities & Fleet Maintenance
vi.      Conservation and Experiential Programming
vii.      Permits, Rentals, and Concessions
viii.      Law Enforcement
ix.      ADA

**Comment by glw** [comment]
Hi @smcalilly on staging Im still seeing the older values or phase values in the the section drop downs, so Im going to re-open this issue so it can be double checked.
