### ISSUE TITLE
investigate weighted score

### ISSUE THREAD

**Issue by smcalilly** [fpdcc/ccfp-asset-dashboard#202]
weighted score average should be between 0 and 5.

**Comment by smcalilly** [comment]
@fgregg here's the relevant code: https://github.com/fpdcc/ccfp-asset-dashboard/blob/master/asset_dashboard/models.py#L336-L355

it looks like it's calculating the total score as expected. here is a stripped down version of that code in a python shell, using the same values of the project where we saw this bug in the demo:
```python
>>> scores = [2, 2, 3, 4, 2, 0]
>>> weights = [0.5, 0.5, 0.3, 0.2, 0.3, 0.3]
>>> total = 0
>>> for score, weight in zip(scores, weights):
...     total += score * weight
...
>>> print(total)
4.3
```

that `4.3` equals [what is on the staging site](https://ccfp-asset-dashboard-staging.herokuapp.com/projects/45/). it would equal > 5 if you tweak the values.

what do we need to change in the calculation so the total is <= 5?

**Comment by fgregg** [comment]
it needs to be

```
for score, weight in zip(scores, weights):
     total += score * weight

total /= sum(weights)
