### ISSUE TITLE
production - only one project can be added to a CIP portfolio

### ISSUE THREAD

**Issue by glw** [fpdcc/ccfp-asset-dashboard#209]
After adding a first project to a portfolio you can no longer add additional projects. Or if you've added your initial project then removed it, it still will not allow you to add additional projects.

![cip_prod_add_proj](https://user-images.githubusercontent.com/556205/178782462-d622eee4-147c-4e03-8e0a-17c9fa09f180.gif)

**Comment by smcalilly** [comment]
this looks like an edge case that was introduced when we changed the calculation panels on the right side of that page. will fix — thanks @glw
