### ISSUE TITLE
Setup app to run on Xavier's local machine

### ISSUE THREAD

**Issue by smcalilly** [fpdcc/ccfp-asset-dashboard#226]
Follow the readme instructions for setting up the app locally. I'll need to share the GIS database with you so that you can load that.

Once the app is running, create a superuser so you can login: `docker-compose run --rm app python manage.py createsuperuser`

Once you're logged in, poke around the app and add some projects, phases, and assets so you can get a sense of the data models and how the interactions work. Then create a CIP portfolio so you can see how that works.

**Comment by xmedr** [comment]
Got it set up!
