### ISSUE TITLE
Check that all GIS model relationships are still valid

### ISSUE THREAD

**Issue by smcalilly** [fpdcc/ccfp-asset-dashboard#243]
From PR #242:
> We need to make sure other tables haven't changed.

Here's the latest schema diagram:
<img width="1458" alt="quercus-6-22-2023" src="https://github.com/fpdcc/ccfp-asset-dashboard/assets/38969506/351be2bd-d540-44f3-b45e-47b6ed34e4f5">

**Comment by smcalilly** [comment]
@xmedr make sure the relationships between the tables in the schema match the model relationships for our current GIS models. we only need it for the models listed here: https://github.com/fpdcc/ccfp-asset-dashboard/blob/master/asset_dashboard/endpoints.py#L65

you should be able to follow the table names within those models and find the matching tables in this schema above. then, if the table has a relationship with another table, you should be able to link the model relationships.

**Comment by xmedr** [comment]
@smcalilly Looks mostly good. I checked the fields and relationships for each just in case, and saw some differences that may or may not be relevant:
- **buildings** 
    - fields: i see `actual_sqft` in the schema, but not in the code ⚠️
    - relationships: none to check ✅
- **trailsinfo**
    - fields: all match ✅
    - relationships:
      - one to many relationship w/`poi_to_trails` in the code, but that says "no longer used" and isn’t on the schema ⚠️
      - all other relationships correct ✅
- **poi_info**
    - fields: all match ✅
    - relationships:
      - two fields `parking_info` and `parking_connection` both are foreign keys to the same `parking_entrance_info` table ⚠️
      - all other relationships correct ✅
- **picnic_groves** 
    - fields: all match ✅ 
    - relationships: all correct ✅
- **misc weirdness?**
    - **poiToTrails** - has a many to one relationship with `poiInfo` and `trailInfo` in `models.py`, but says it is "no longer used" and that relationship is not shown in the schema ⚠️
