### ISSUE TITLE
Asset list page navigation not working

### ISSUE THREAD

**Issue by hallj89** [fpdcc/ccfp-asset-dashboard#273]
![image](https://github.com/fpdcc/ccfp-asset-dashboard/assets/15983603/49e304a2-3029-4db2-b473-0cea79aae1c7)

Buttons to advance to next page/ skip to end not working.

**Comment by smcalilly** [comment]
@hallj89 forgot to mention this bug in our meeting! We'll fix this asap.

**Comment by smcalilly** [comment]
I was able to recreate this on the staging app: https://ccfp-asset-dashboard-staging.herokuapp.com/projects/428/

We have a similar table on the edit assets page, but the bug isn't happening: https://ccfp-asset-dashboard-staging.herokuapp.com/projects/phases/edit/811/assets/

**Comment by smcalilly** [comment]
shoot, can't recreate on my local machine :(
