### ISSUE TITLE
Edit assets from phase ui

### ISSUE THREAD

**Issue by smcalilly** [fpdcc/ccfp-asset-dashboard#94]
The asset selection tool needs to be associated with a phase and accessible through the phase form UI.

Should be able to
- select a phase
- then access the asset tool

**Comment by smcalilly** [comment]
@fgregg Two questions:

1. With this change, do we still need the "Assets" tab in the UI?
![Screen Shot 2022-01-26 at 9 59 03 AM](https://user-images.githubusercontent.com/38969506/151199077-c854d9ab-3eb5-4ccc-a477-81951e775c10.png)

2. Will [the assets list view](https://app.moqups.com/oyzaWsCDbsZ7xXShLNvzgbpzpBoQ8D1s/edit/page/ad64222d5) link from a phase, too? How would a user access that? I'm wondering what the sequence is (phase -> link to the edit tool, then a link to the list view?) Maybe that page isn't even necessary since we have a list of the assets in the asset tool?

**Comment by fgregg** [comment]
i think we don't need the assets tab in the UI. 

i think on the phase view, we might want a map, and then maybe not a separate listing?
