### ISSUE TITLE
Toogle for editing mode vs navigation mode

### ISSUE THREAD

**Issue by smcalilly** [fpdcc/ccfp-asset-dashboard#97]
Here's an example that lets you toggle different types of interactions: https://geojson.io/#map=3/38.89/-81.21

**Comment by smcalilly** [comment]
This ^ toggle example comes out of the box with the Leaflet.draw plugin. [The react-leaflet-draw library](https://github.com/alex3165/react-leaflet-draw#readme) is the react version of that, and those layer controls are also included. So, I'll introduce that library so that we can have the toggling. Using this library will also give us the ability to draw more dynamic polygons (based on notes from our meeting with Garret, [written down here](https://github.com/fpdcc/ccfp-asset-dashboard/issues/63#issuecomment-1013248556))

**Comment by fgregg** [comment]
sweeeet!
